version: 1
accounts:
  - name: alice
    coins: ["2000000000000utoken"]
  - name: bob
    coins: ["10000000000utoken"]
validators:
  - name: alice
    bonded: "1000000000000utoken"
client:
  typescript:
    path: "ts-client"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "utoken"
    mint:
      params:
        mint_denom: "utoken"